### ISSUE TITLE
为什么时候key 就可以  使用 就 name

### ISSUE THREAD

**Issue by qa1057** [StructureBuilder/react-keep-alive#10]
在KeepAlive 中 使用name属性 来回切换组件 就报错。使用key就不报错

**Comment by Sam618** [comment]
@qa1057 能给我看下代码示例吗？ 另外可以参考下 [keepAliveDecorator.tsx](https://github.com/StructureBuilder/react-keep-alive/blob/master/src/utils/keepAliveDecorator.tsx) 的 `271` 行。

**Comment by Sam618** [comment]
@qa1057 修复好了，请安装最新版本
