### ISSUE TITLE
与 react-loadable 无法一起使用

### ISSUE THREAD

**Issue by zhang504988670** [StructureBuilder/react-keep-alive#11]
react-router 与 react-router-dom 都是5.0.0
![image](https://user-images.githubusercontent.com/18161513/56404037-0382d380-6297-11e9-91ad-15b5917337c6.png)

**Comment by Sam618** [comment]
@zhang504988670 能给我看下复现示例吗

**Comment by Sam618** [comment]
@zhang504988670 可以参考 #3
