### ISSUE TITLE
感觉你上传的包是不是有错误呢？

### ISSUE THREAD

**Issue by Jackie-Web** [StructureBuilder/react-keep-alive#12]
我引用你的包会报这个错误。
![image](https://user-images.githubusercontent.com/11611057/56662597-f458b700-66d6-11e9-8428-51e42e82502b.png)

但是我直接用你的源码是不会报这个错误的。

**Comment by Sam618** [comment]
@Jackie-Web 感谢提出问题😄，能给我一份可以复现的源码吗，我来测试下哈

**Comment by Jackie-Web** [comment]
上面的问题我只有在我自己项目下引用npm包后会报错，但是用你的demo去引就不会报错。不太清楚是哪里出的问题。我也在找原因。
还有另外的一个错误，如果把react-router-dom下的Link跳转包裹在
<KeepAlive></KeepAlive> 这里 就会发生报错。
例子
![image](https://user-images.githubusercontent.com/11611057/56703872-7d0a3e00-673d-11e9-8d34-73d122a1e225.png)
![image](https://user-images.githubusercontent.com/11611057/56703887-8a272d00-673d-11e9-87ee-74f7da45ac5c.png)

react-router@5.0.0
react-router-dom@5.0.0

**Comment by Jackie-Web** [comment]
你好，我是在github上提出issues的 如果方便可以加一个 QQ或者微信吗？ 我这边引用你的包还是会报错，但是我找不到什么原因，可能还需要你帮我来解惑一下，在github上交流很慢。

**Comment by Jackie-Web** [comment]
我的QQ号是 276123755

**Comment by Sam618** [comment]
@Jackie-Web 
![image](https://user-images.githubusercontent.com/24489287/56711861-d46cd600-675e-11e9-9847-cda94302fe10.png)
试试把 `Provider` 放在 `Router` 组件里面。

**Comment by Jackie-Web** [comment]
放在里面可用用了。但是我一直没搞懂 我引用你的包 会报我第一次截图的那个错误，感觉好像引用方式出错了，但是完全找不到原因，我把你的包拉到项目里了引用就没问题~要不要我们加个联系方式？我给你演示看看。

**Comment by Sam618** [comment]
@Jackie-Web 嗯嗯，加我微信吧 s2696922797c
