### ISSUE TITLE
经过滚动条页面后，发现有bug

### ISSUE THREAD

**Issue by amazingzcj** [StructureBuilder/react-keep-alive#13]
用了antd样式，然后发现为什么缓存了之后，只要选择了有滚动条的页面，然后进入其他页面，发现底部有空白区，这怎么解决？

**Comment by Sam618** [comment]
@amazingzcj 正在修复中，马上放出最新版本

**Comment by amazingzcj** [comment]
> @amazingzcj 正在修复中，马上放出最新版本

非常感谢！

**Comment by Sam618** [comment]
@amazingzcj `npm install react-keep-alive@latest`，已经发布最新版本

**Comment by amazingzcj** [comment]
@Sam618 谢谢大大！目前试了下没什么问题，就是切换到缓存的页面的时候，会有一些些卡顿。还想咨询下，是不是`<KeepAlive>`组件必须嵌套在`<Route>`组件中，例如：`<Route render={()=>(<KeepAlive>)}>`这样写似乎会报错。

**Comment by amazingzcj** [comment]
有一个新问题：cache页面来回跳转似乎会出现这个情况。
![error](https://user-images.githubusercontent.com/35787666/57598625-80e3f000-7586-11e9-9772-16111f135cfe.png)

**Comment by Sam618** [comment]
@amazingzcj 能给我一个 demo 看下吗😁

**Comment by Sam618** [comment]
> @Sam618 谢谢大大！目前试了下没什么问题，就是切换到缓存的页面的时候，会有一些些卡顿。还想咨询下，是不是`<KeepAlive>`组件必须嵌套在`<Route>`组件中，例如：`<Route render={()=>(<KeepAlive>)}>`这样写似乎会报错。

`<KeepAlive>` 组件不一定要放在 `<Route>` 组件中，但是 `<KeepAlive>` 组件里面必须要有一个组件，并且这个组件的最外层必须有一个真实 DOM 的标签（例如 `<div>`）。

**Comment by amazingzcj** [comment]
一个demo,可能会有些乱= =
来回点击侧边栏按钮切换组件似乎有些问题.




------------------ 原始邮件 ------------------
发件人: "Shen Chang"<notifications@github.com>;
发送时间: 2019年5月13日(星期一) 下午2:56
收件人: "StructureBuilder/react-keep-alive"<react-keep-alive@noreply.github.com>;
抄送: "amazingzcj"<996146632@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [StructureBuilder/react-keep-alive] 经过滚动条页面后，发现有bug (#13)




@amazingzcj 能给我一个 demo 看下吗😁

**Comment by Sam618** [comment]
> 一个demo,可能会有些乱= = 来回点击侧边栏按钮切换组件似乎有些问题.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Shen Chang"<notifications@github.com>; 发送时间: 2019年5月13日(星期一) 下午2:56 收件人: "StructureBuilder/react-keep-alive"<react-keep-alive@noreply.github.com>; 抄送: "amazingzcj"<996146632@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [StructureBuilder/react-keep-alive] 经过滚动条页面后，发现有bug (#13) @amazingzcj 能给我一个 demo 看下吗😁 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

这样发的文件好像有问题，我没收到，要不你发我邮箱吧 `s2696922797c@outlook.com` 😂

**Comment by amazingzcj** [comment]
已发！非常感谢作者大大


------------------ 原始邮件 ------------------
发件人: "Shen Chang"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 上午9:15
收件人: "StructureBuilder/react-keep-alive"<react-keep-alive@noreply.github.com>;
抄送: "amazingzcj"<996146632@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [StructureBuilder/react-keep-alive] 经过滚动条页面后，发现有bug (#13)



 
一个demo,可能会有些乱= = 来回点击侧边栏按钮切换组件似乎有些问题.
 …
 ------------------ 原始邮件 ------------------ 发件人: "Shen Chang"notifications@github.com; 发送时间: 2019年5月13日(星期一) 下午2:56 收件人: "StructureBuilder/react-keep-alive"react-keep-alive@noreply.github.com; 抄送: "amazingzcj"996146632@qq.com;"Mention"mention@noreply.github.com; 主题: Re: [StructureBuilder/react-keep-alive] 经过滚动条页面后，发现有bug (#13) @amazingzcj 能给我一个 demo 看下吗😁 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
  
这样发的文件好像有问题，我没收到，要不你发我邮箱吧 s2696922797c@outlook.com 😂

**Comment by Sam618** [comment]
@amazingzcj 已经升级到 `2.0.1` 版本，修复了这个问题

**Comment by amazingzcj** [comment]
@Sam618 好的，非常感谢！👍

**Comment by amazingzcj** [comment]
@Sam618 今天重试了一下，发现首次渲染内容是空的，dom似乎没有加载上，是因为生命周期的缘故吗？

![nocontent](https://user-images.githubusercontent.com/35787666/57824558-0a393380-77ce-11e9-9d3a-6ddba3adf876.png)

**Comment by amazingzcj** [comment]
@Sam618 抱歉，忘记在外面嵌套<div>😂，目前无问题！感谢！

**Comment by Sam618** [comment]
@amazingzcj 升级下最新版本看
