### ISSUE TITLE
问下使用了keep-alive 是不是没办用withRouter

### ISSUE THREAD

**Issue by Paul0523** [StructureBuilder/react-keep-alive#15]
我看了下 回报错
Uncaught (in promise) Error: Invariant failed: You should not use <Route> outside a <Router>
![image](https://user-images.githubusercontent.com/11917690/57908827-9f622800-78b3-11e9-912b-0493620ceff3.png)
![image](https://user-images.githubusercontent.com/11917690/57908846-ad17ad80-78b3-11e9-80ad-7807897a2c79.png)
![image](https://user-images.githubusercontent.com/11917690/57908881-c6b8f500-78b3-11e9-970e-95577e67eac8.png)

**Comment by Sam618** [comment]
@Paul0523 尝试使用 `react-router-dom` 库
