### ISSUE TITLE
Linux下打包出现异常

### ISSUE THREAD

**Issue by Estelle00** [StructureBuilder/react-keep-alive#2]
作者您好，
操作系统：CentOS 7.5
node: 10.15.3
打包工具：umi
生成文件出现
![image](https://user-images.githubusercontent.com/5432828/54799591-d5f73a00-4c98-11e9-8c31-4b4a3490cabe.png)
错误位置
https://github.com/StructureBuilder/react-keep-alive/blob/e95cef41d72793973f4cf85272c0513d65359300/src/utils/keepAlive.tsx#L278
debug发现此处 cache值为undefined
ps: windows环境测试没问题

**Comment by Estelle00** [comment]
@Sam618

**Comment by Sam618** [comment]
感谢提出问题，能看下发现问题的代码吗？

**Comment by Estelle00** [comment]
demo  https://github.com/Estelle00/demo
dist为在centos下打包生成的文件
 访问/地址会报错，
404页面未使用keepAlive未报错

**Comment by Sam618** [comment]
```JavaScript
import { Button } from "antd-mobile";
import React, { PureComponent } from "react";
import { KeepAlive } from "react-keep-alive";
import router from "umi/router";
class Index extends PureComponent<any> {
  public render() {
    return (
        <div>
          <Button onClick={e => router.push("/404")} inline type="primary" size={"small"}>test</Button>
        </div>
    );
  }
}

function Wrapper(props) {
  return (
      <KeepAlive key="home">
        <Index {...props} />
      </KeepAlive>
  );
}

export default Wrapper;
```
试试这个代码看

**Comment by Estelle00** [comment]
@Sam618 问题依然存在

**Comment by Sam618** [comment]
@Estelle00 找到问题了，你提供的 DEMO 中 `src/layouts` 目录下的 `Index.tsx` 写错了，应该改成 `index.tsx`，这样才能让 umi 识别，否则并不会加载这个文件，具体请看 [src/layouts/index.js](https://umijs.org/zh/guide/app-structure.html#src-layouts-index-js)。

**Comment by Estelle00** [comment]
果然是，谢谢大佬
