### ISSUE TITLE
如果对Route封装一层AuthRouter，貌似不起作用了

### ISSUE THREAD

**Issue by luguiqing** [StructureBuilder/react-keep-alive#20]

**Comment by luguiqing** [comment]
`class AuthRouter extends React.Component {
  render() {
    const { permissionPath } = this.props
    return (
      <Auth permissionPath={permissionPath} >
        <Route { ...this.props }></Route>
      </Auth>
    )
  }
}`

Auth组件则是用过判断用户是否有权限，没有权限则进行重定向
这样我不知道如何用你的keepalive了

**Comment by Sam618** [comment]
@luguiqing 
```JavaScript
class AuthRouter extends React.Component {
  render() {
    const {
      children,
      permissionPath
    } = this.props
    return ( 
      <Auth 
        permissionPath={permissionPath}
      > 
        <Route {...this.props}>
      </Auth > 
    )
  }
}

<AuthRouter render={() => (
  <KeepAlive>...</KeepAlive>
)} />
```
和原来的用法是一致的
