### ISSUE TITLE
KeepAlive包裹的组件，当中如果有state，只会渲染初始值，当state改变的时候不能更新

### ISSUE THREAD

**Issue by zyno1107** [StructureBuilder/react-keep-alive#21]
const [value,setValue] = useState('');   
   const change = (e) => {
        setValue(e.target.value);
    }
    return (
        <div>
            <KeepAlive name='pageA'>
                <p><input onChange={(e) => { change(e) }} /></p>
                <p>value:{value}</p>
            </KeepAlive>
        </div>
    )
这样子的话，value只会渲染初始值，后面的不再渲染。有什么办法使得KeepAlive里面的state能实时更新。
（项目中有个情景：一个列表，数据通过useState保存，当前第一页，点击到第二页的时候，state会更新，但是列表组件放在KeepAlive 中会无法更新）

请问这个有什么好的解决办法不

**Comment by Sam618** [comment]
@zyno1107  可以给我发个 DEMO

**Comment by Loviy** [comment]
这个问题解决了吗？担心用了之后也会出现这情况，不敢用...

**Comment by Sam618** [comment]
希望能发个 DEMO 给我，我来测试一下

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Loviy <notifications@github.com>
发送时间: Thursday, June 27, 2019 10:24:34 AM
收件人: StructureBuilder/react-keep-alive
抄送: Shen Chang; Comment
主题: Re: [StructureBuilder/react-keep-alive] KeepAlive包裹的组件，当中如果有state，只会渲染初始值，当state改变的时候不能更新 (#21)


这个问题解决了吗？担心用了之后也会出现这情况，不敢用...

―

**Comment by Loviy** [comment]
谢谢，我只是看到有人提出这问题
我还没有使用，所以我没有demo


------------------ 原始邮件 ------------------
发件人: "Shen Chang"<notifications@github.com>;
发送时间: 2019年6月27日(星期四) 晚上7:07
收件人: "StructureBuilder/react-keep-alive"<react-keep-alive@noreply.github.com>;
抄送: "WO"<928739110@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [StructureBuilder/react-keep-alive] KeepAlive包裹的组件，当中如果有state，只会渲染初始值，当state改变的时候不能更新 (#21)



希望能发个 DEMO 给我，我来测试一下 
 
 发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用 
 
 ________________________________ 
 发件人: Loviy <notifications@github.com> 
 发送时间: Thursday, June 27, 2019 10:24:34 AM 
 收件人: StructureBuilder/react-keep-alive 
 抄送: Shen Chang; Comment 
 主题: Re: [StructureBuilder/react-keep-alive] KeepAlive包裹的组件，当中如果有state，只会渲染初始值，当state改变的时候不能更新 (#21) 
 
 
 这个问题解决了吗？担心用了之后也会出现这情况，不敢用... 
 
 ―

**Comment by Sam618** [comment]
@Loviy @zyno1107 可以参考下这个例子 [useKeepAliveEffect](https://codesandbox.io/s/yp6qjk1vw1)
