### ISSUE TITLE
TS编译错

### ISSUE THREAD

**Issue by lxyisme** [StructureBuilder/react-keep-alive#28]
### 报错截图：
![image](https://user-images.githubusercontent.com/25142497/62613516-2adfd800-b93c-11e9-898d-f5b5f569b4b2.png)

### 测试代码：
```
<Provider include="CustomerDetails">
      <KeepAlive name="CustomerDetails">
        <div>CustomerDetails</div>
      </KeepAlive>
</Provider>
// 未使用router
```
### react-keep-alive 版本：
- v2.1.0

**Comment by lxyisme** [comment]
刚发现只要在项目内引入组件就会报错，错误相同

**Comment by Sam618** [comment]
@lxyisme 改好了，版本升级到了 `2.2.0`，感谢提出问题哈😀
