### ISSUE TITLE
报错了,是与react-loadable有冲突吗?

### ISSUE THREAD

**Issue by LastStranger** [StructureBuilder/react-keep-alive#3]
![image](https://user-images.githubusercontent.com/29811304/55223041-4af1e300-5248-11e9-84c9-fd498a3b9508.png)
![image](https://user-images.githubusercontent.com/29811304/55223084-60ffa380-5248-11e9-965d-0688f6208ce4.png)
![image](https://user-images.githubusercontent.com/29811304/55223123-77a5fa80-5248-11e9-969a-bf523fe3c3cf.png)
![image](https://user-images.githubusercontent.com/29811304/55223210-aa4ff300-5248-11e9-84e3-22bc78bd27af.png)

react-router 4.2.0
react-router-dom4.2.2

**Comment by Sam618** [comment]
@LastStranger react-router 必须使用最新版本，请使用下面方式安装：`npm install react-router react-router-dom`。现在的 react-router 最新版是 5.0.0，使用了 new Context API，而 react-keep-alive 也是使用的 new Context API，这样是可以传递数据的，旧的 Context API 不行。

**Comment by LastStranger** [comment]
还是一样的错误,我不使用react-loadable就是好的

**Comment by LastStranger** [comment]
我感觉问题就出在react-loadable上,
![image](https://user-images.githubusercontent.com/29811304/55719370-abdf9f00-5a30-11e9-9002-59297a612b68.png)
我react-router和react-router-dom都是5.0.0,可能keepAlive在react-loadable中不是这样写的

**Comment by LastStranger** [comment]
之前我直接在LadableAppGetUserInfo外加了一层KeepAlive,然后就报错了

**Comment by Sam618** [comment]
@LastStranger 很抱歉这么晚回复，希望下次能重新开个 ISSUE 啦😂，具体解决方案：[With React Loadable](https://codesandbox.io/s/3r5331vjl1)。
