### ISSUE TITLE
作者能否提供一个手动清空缓存的api

### ISSUE THREAD

**Issue by 704826318** [StructureBuilder/react-keep-alive#32]
因为要考虑到切换用户重新登入时，页面缓存可能要重置到用户刚进入时的状态。
想问下有没有什么方法能手动清空页面缓存

**Comment by Vikingama** [comment]
用户退出登陆时，跳转刷新页面

**Comment by Sam618** [comment]
@704826318 或许可以看下这个例子 [Control cache](https://codesandbox.io/s/llp50vxnq7)，文档中介绍了这个组件 [Provider](https://github.com/StructureBuilder/react-keep-alive#provider)（[Provider 中文文档](https://github.com/StructureBuilder/react-keep-alive/blob/master/README.zh-CN.md#provider)）。

这个需求通过 `<Provider>` 组件实现，大致流程如下：
1. 通过变量（可以是 state 或者 redux 等数据管理工具的数据）设置 `<Provider>` 的 `include` 或者 `exclude` 属性，需要注意 `include` 和 `exclude` 只能使用一个。
2. 在切换到用户登录界面时，更改变量的值，例如使用的是 `include` 属性，那么就在变量中把需要缓存的页面去掉，这样下次再进入时，页面就没有缓存了。
更加详尽的代码可以看我上面的示例。😄

**Comment by Sam618** [comment]
@Vikingama 刷新页面可能体验不会很好，优化可以考虑上面的回答😃

**Comment by 704826318** [comment]
> @Vikingama 刷新页面可能体验不会很好，优化可以考虑上面的回答😃

ts里面会出现语法报错
```
作为表达式调用时，无法解析类修饰器的签名。
  不能将类型“ForwardRefExoticComponent<Pick<any, string | number | symbol> & RefAttributes<{}>> & { contextType: Context<any> | undefined; getDerivedStateFromError: GetDerivedStateFromError<any, any> | undefined; }”分配给类型“typeof OrderList”。
    类型“ForwardRefExoticComponent<Pick<any, string | number | symbol> & RefAttributes<{}>> & { contextType: Context<any> | undefined; getDerivedStateFromError: GetDerivedStateFromError<any, any> | undefined; }”提供的内容与签名“new (props: any): OrderList”不匹配。ts(1238)

import { bindLifecycle } from 'react-keep-alive';

@bindLifecycle
export default class OrderList extends PureComponent<any, any> {

```

**Comment by Sam618** [comment]
> > @Vikingama 刷新页面可能体验不会很好，优化可以考虑上面的回答😃
> 
> ts里面会出现语法报错
> 
> ```
> 作为表达式调用时，无法解析类修饰器的签名。
>   不能将类型“ForwardRefExoticComponent<Pick<any, string | number | symbol> & RefAttributes<{}>> & { contextType: Context<any> | undefined; getDerivedStateFromError: GetDerivedStateFromError<any, any> | undefined; }”分配给类型“typeof OrderList”。
>     类型“ForwardRefExoticComponent<Pick<any, string | number | symbol> & RefAttributes<{}>> & { contextType: Context<any> | undefined; getDerivedStateFromError: GetDerivedStateFromError<any, any> | undefined; }”提供的内容与签名“new (props: any): OrderList”不匹配。ts(1238)
> 
> import { bindLifecycle } from 'react-keep-alive';
> 
> @bindLifecycle
> export default class OrderList extends PureComponent<any, any> {
> ```

已修复

**Comment by 704826318** [comment]
作者我又发现一个问题，一个页面被设置了`disabled={true}` ，页面是取消了缓存，但是页面内的子组件`state`数据还存在缓存问题

**Comment by Sam618** [comment]
> 作者我又发现一个问题，一个页面被设置了`disabled={true}` ，页面是取消了缓存，但是页面内的子组件`state`数据还存在缓存问题

感谢提出问题😄，能给我发一份 DEMO 吗？我排查一下问题

**Comment by 704826318** [comment]
> > 作者我又发现一个问题，一个页面被设置了`disabled={true}` ，页面是取消了缓存，但是页面内的子组件`state`数据还存在缓存问题
> 
> 感谢提出问题😄，能给我发一份 DEMO 吗？我排查一下问题

我知道问题了，是我的自己逻辑有问题😅

**Comment by Sam618** [comment]
> > > 作者我又发现一个问题，一个页面被设置了`disabled={true}` ，页面是取消了缓存，但是页面内的子组件`state`数据还存在缓存问题
> > 
> > 
> > 感谢提出问题😄，能给我发一份 DEMO 吗？我排查一下问题
> 
> 我知道问题了，是我的自己逻辑有问题😅

嗯嗯，好哒😁
