### ISSUE TITLE
Warning is Ok? 

### ISSUE THREAD

**Issue by Vikingama** [StructureBuilder/react-keep-alive#33]
Thank you for this gorgeous component, v2.4 works well with next.js v9.0. But I counter a warning in the console tab in chrome, is a feature or a bug?

![image](https://user-images.githubusercontent.com/26019582/62998867-5d8b5280-be9f-11e9-9630-1f0188e89543.png)

**Comment by Sam618** [comment]
@Vikingama Thank you. When will the warning appear? For example, will this warning appear immediately after the page is rendered?
