### ISSUE TITLE
引入keep-alive无法使用 路由内部抛错出来

### ISSUE THREAD

**Issue by ErnestWangZuNian** [StructureBuilder/react-keep-alive#34]
错误提示: react-dom.production.min.js:110 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

代码 
import { HashRouter, Route, Switch } from 'react-router-dom';
import {
  Provider as KeepAliveProvider,
  KeepAlive,
} from 'react-keep-alive';

import App from '../pages/app';
import Demo from '../pages/demo';

const Router = (
  <HashRouter>
    <KeepAliveProvider>
      <Switch>
        <Route path="/" exact>
          <KeepAlive name="One">
            <App />
          </KeepAlive>
        </Route>
        <Route path="/demo" exact>
          <KeepAlive name="Demo">
            <Demo />
          </KeepAlive>
        </Route>
      </Switch>
    </KeepAliveProvider>
  </HashRouter>
);
export default Router;

main.js

import Api from './api/index';
import Util from './utils';

import Router from './routes';
import 'antd/dist/antd.css';

Object.assign(global, antd);
global.Api = Api;
global.Util = Util;

ReactDOM.render(
  Router,
  document.getElementById('app'),
);

**Comment by Sam618** [comment]
@ErnestWangZuNian 抱歉，上面的代码有些省略；能把 `Router` 的一部分给我看下或者提供一份更为详细的 DEMO 给我测试下吗？

**Comment by ErnestWangZuNian** [comment]
###  版本信息如下
```js
   "react-keep-alive": "^2.4.1",
   "react-redux": "^7.0.3",
   "react-router-dom": "^5.0.1",
```
###  不好意思 白天有点忙 昨天粘贴代码时没注意  router代码如下 
```js
import { HashRouter, Route, Switch } from 'react-router-dom';
import {
  Provider,
  KeepAlive,
} from 'react-keep-alive';
// import asyncComponent from "../components/bundle"
import App from '../pages/app';
import Demo from '../pages/demo';

// const App = asyncComponent(() => import('../pages/app'));
// const Demo = asyncComponent(() => import('../pages/demo'));

const Router = (
  <HashRouter>
    <Provider>
      <Switch>
        <Route
          path="/"
          exact
          render={props => (
            <KeepAlive name="app">
              <App {...props} />
            </KeepAlive>
          )}
        />
        <Route
          path="/demo"
          exact
          render={props => (
            <KeepAlive name="demo">
              <Demo {...props} />
            </KeepAlive>
          )}
        />
      </Switch>
    </Provider>
  </HashRouter>


);
export default Router;
```

**Comment by Sam618** [comment]
@ErnestWangZuNian 看上去没啥问题,尝试看下 [Online Editor](https://github.com/StructureBuilder/react-keep-alive/blob/master/ONLINE_EDITOR.md) 的代码,如果还是不行,可以发一份 DEMO 给我测试一下哈😄
