### ISSUE TITLE
限制keep alive数量

### ISSUE THREAD

**Issue by xcqwan** [StructureBuilder/react-keep-alive#45]
考虑到keep alive的组件不会被回收，将常驻内存，如果用户长时间使用，势必会存在占用大量内存。因此希望可以有办法限制alive组件数量。
尝试过动态修改provider的include，不过不生效。建议可以在include值变化后，清理不符合include规则的alive组件移除。
@Sam618 麻烦看下有没有什么办法解决，实际工程中应用比较迫切需要解决的问题

**Comment by Sam618** [comment]
@xcqwan 嗯嗯，非常实际的问题，以前也考虑过这个问题；我想一下如何解决！

**Comment by xcqwan** [comment]
@Sam618 有进展吗？

**Comment by ShenChang618** [comment]
@xcqwan 已经好了，最新版本是 2.5.2，抱歉忘记提交到 github 了

**Comment by xcqwan** [comment]
@Sam618 好的，赞!
