### ISSUE TITLE
disable属性不太会用

### ISSUE THREAD

**Issue by xiejingpeng** [StructureBuilder/react-keep-alive#48]
在工作中，由详情页调到列表页，列表页需要缓存，但从修改业到列表页，列表页不需要缓存，需要动态控制，麻烦能不能给个demo，关于disable的

**Comment by ShenChang618** [comment]
@xiejingpeng 文档中有 Online Editor，里面有 DEMO 的，[Control cache](https://codesandbox.io/s/llp50vxnq7)

**Comment by xiejingpeng** [comment]
感谢，没问题啦
