### ISSUE TITLE
问下小伙伴们对于现在的生命周期有没有什么好的建议！

### ISSUE THREAD

**Issue by Sam618** [StructureBuilder/react-keep-alive#5]
现在的生命周期，我认为其实有些怪异：
```
Mounting: componentWillMount -> componentDidMount
Unmounting: componentWillUnmount

Activating: componentWillUpdate -> componentDidMount(This is where the user is confused. I am tampering with the life cycle when I activate it.)
Unactivating: componentWillUnmount
```
在 Activating 时，其实组件并没有真正的卸载掉，所以能够保存组件实例中的状态；这个阶段本来的执行顺序是 `componentWillUpdate -> componentDidUpdate`，但是为了方便，我更改了生命周期，这样就与 React 的生命周期有些不一样，不知道大家能否接受，希望能提出一些建议😄。

**Comment by Estelle00** [comment]
还是希望与原生命周期一致；
因为现在这个周期问题 引发antd-mobile的SearchBar组件初始化异常。

index页面使用的keep-alive初始化异常， 404页面未使用初始化正常。
demo如下：
https://github.com/Estelle00/demo/blob/8be2a10b7cd945500c64edc45c983b48c93c3370/src/pages/index/index.tsx

**Comment by Sam618** [comment]
@Estelle00 我 clone 了 demo，并没有发现问题，能给我看下报错吗😂，你的环境是？

**Comment by Estelle00** [comment]
@Sam618 
首页异常样式
![image](https://user-images.githubusercontent.com/5432828/56875062-ddb4b600-6a70-11e9-9938-0017e0c6f0e1.png)
404页面正常样式
![image](https://user-images.githubusercontent.com/5432828/56875083-fde47500-6a70-11e9-822d-ad162464a61a.png)

**Comment by Sam618** [comment]
@Estelle00 这个问题是因为组件初期会挂载到一个设置为 `display: none` 的节点上，因此不能获取到正确的盒模型信息，晚些时候，我会修复这个 BUG😄。

**Comment by Estelle00** [comment]
@Sam618 好的 谢谢 大佬

**Comment by Sam618** [comment]
@Estelle00 可以下载最新版本试试啦

**Comment by Estelle00** [comment]
@Sam618 这样的处理方式好像不对，如果使用window滚动方式，缓存组件高度过长情况下 会出现新页面高度异常

**Comment by Estelle00** [comment]
https://github.com/StructureBuilder/react-keep-alive/blob/1ed0cf2f128243e53d116d41c41761b6524ca78b/src/utils/createStoreElement.ts#L6-L11
是否考虑在上面添加两个东东：
```
  keepAliveDOM.style.height= '0';
  keepAliveDOM.style.overflow= 'hidden';
```

**Comment by Sam618** [comment]
@Estelle00 我发现这样还是会有 BUG，所以我需要再考虑下怎么做😂

**Comment by Bigmuggle** [comment]
若果使用 antd pro 的那套脚手架 该怎么用呢

**Comment by Bigmuggle** [comment]
@Estelle00

**Comment by Sam618** [comment]
@Estelle00 已经发布最新版本，修复了这些问题 `npm install react-keep-alive@latest`
