### ISSUE TITLE
使用react-router-config路由跳转的时候报错，Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by ghost** [StructureBuilder/react-keep-alive#50]
`
                    <KeepAlive name="admin">
                        {renderRoutes(route.routes)}
                    </KeepAlive>
`

报错信息如下图
![image](https://user-images.githubusercontent.com/22910677/65736716-a2e1a780-e10e-11e9-92af-4131ed33d5d2.png)

**Comment by ShenChang618** [comment]
@hum-tan 可以给我一个 DEMO 吗，我测试一下

**Comment by ghost** [comment]
@Sam618 我把<KeepAlive>放在路由对应的组件里面就不会报错了

**Comment by jiangyh123456** [comment]
@hum-tan 
你怎么解决的啊

**Comment by jiangyh123456** [comment]
![image](https://user-images.githubusercontent.com/58922907/72510192-f3c70880-3883-11ea-805c-96cfc39cff02.png)
![image](https://user-images.githubusercontent.com/58922907/72510260-13f6c780-3884-11ea-9bb1-273e95281bc8.png)

![image](https://user-images.githubusercontent.com/58922907/72510209-f88bbc80-3883-11ea-9aef-8e10d113f32b.png)


我这样 会报错
![image](https://user-images.githubusercontent.com/58922907/72510234-05a8ab80-3884-11ea-8050-5aa666bc13b9.png)

**Comment by ShenChang618** [comment]
@jiangyh123456 `<KeepAlive />` 里面放一个 `<div />`，然后把 `<ProccessComponent />` 组件放到 `<div />` 里面试试。

**Comment by jiangyh123456** [comment]
@Sam618 
![image](https://user-images.githubusercontent.com/58922907/72575778-7c878800-3908-11ea-83e7-659fb48d7fe7.png)
div 包住keepalive 就行了。。。

**Comment by ShenChang618** [comment]
@jiangyh123456 因为是加载中的组件，这个时候是没有 DOM 的，所以会报错。

**Comment by jiangyh123456** [comment]
@Sam618  组件里面使用了 iframe 显示一个网页 比如百度  切换之后 貌似 网页是重新加载的

**Comment by ShenChang618** [comment]
@jiangyh123456 iframe 应该会重新渲染的，因为 react-keep-alive 的原理说起来也简单，就是把 DOM 保存起来，然后进行恢复，其实就是 removeChild 和 appendChild 来操作 DOM，所以可以发现滚动条也是不能保存位置的。

**Comment by jiangyh123456** [comment]
@Sam618 好的 谢谢

**Comment by ShenChang618** [comment]
@jiangyh123456 不客气哈，有问题可以加我微信 s2696922797c，Github 我不一定能看到

**Comment by jiangyh123456** [comment]
好
