### ISSUE TITLE
@bindLifecycle  会导致每个路由都渲染一次 （render函数会执行多次） 怎么处理

### ISSUE THREAD

**Issue by joyhao** [StructureBuilder/react-keep-alive#53]
![image](https://user-images.githubusercontent.com/11315770/65829700-990c9f80-e2da-11e9-92a9-0f57ade2f66e.png)

![image](https://user-images.githubusercontent.com/11315770/65829713-b5104100-e2da-11e9-88d4-a96674f99673.png)

**Comment by ShenChang618** [comment]
@joyhao 在渲染的过程中 render 函数执行多次应该问题不大，在 render 函数中只是返回了 React 的 Element，实际渲染只会有一次。

**Comment by joyhao** [comment]
欧克
