### ISSUE TITLE
大哥能不能给你提个小小的需求：不缓存React-Router的信息

### ISSUE THREAD

**Issue by zhoutengshen** [StructureBuilder/react-keep-alive#57]
项目里面部分地方用到路由里面的参数，每次componentDidActivate的时候获取到的路由信息（参数）都是一样的。虽然可以通过extra 解决。但是部分网络请求的需要的路由参数在React-Redux的connect的mapDipatchToPRops里面。。。或者你有什么高见（PS新手一枚）

**Comment by ShenChang618** [comment]
@zhoutengshen 尝试一下 [react-router-redux](https://github.com/reactjs/react-router-redux) 看

**Comment by zhoutengshen** [comment]
> @zhoutengshen 尝试一下 [react-router-redux](https://github.com/reactjs/react-router-redux) 看

好，谢谢大佬。
