### ISSUE TITLE
disabled属性变动时，componentWillUnmount异常的问题

### ISSUE THREAD

**Issue by Chenjiayuan195** [StructureBuilder/react-keep-alive#58]
我在使用时遇到一个问题，就是当disabled属性从false变为true时，组件的componentWillUnmount能够正常触发，但是其子组件的componentWillUnmount不会触发，而是会在下一次进来的时候才触发？请问这个问题现在有解决方案吗，十分感谢

**Comment by ShenChang618** [comment]
@Chenjiayuan195 有的哈，可以看一下 [bindLifecycle](https://github.com/StructureBuilder/react-keep-alive/blob/master/README.zh-CN.md#bindlifecycle)，子组件绑定这个 API 之后会增加两个新的生命周期。

**Comment by Chenjiayuan195** [comment]
那就是我所有在本组件内用到的子组件都需要进行bindLifecycle对吧

**Comment by Chenjiayuan195** [comment]
还有一个问题，目前我的项目需要兼容到ie9，好像该组件在ie9上会报错，想知道作者这边有什么解决方案吗

**Comment by ShenChang618** [comment]
@Chenjiayuan195 在你需要这两个生命周期的子组件上使用 bindLifecycle 就可以啦，IE 9 要看 React 支不支持，版本必须要 React 16.3+ 才行呢😊
