### ISSUE TITLE
手动移除缓存

### ISSUE THREAD

**Issue by fisher-zwl** [StructureBuilder/react-keep-alive#64]
比如：俩个页面组件切换使用缓存，当关掉一个页面然后重新打开这个页面组件希望组件重新激活，清掉上次的缓存

**Comment by 15108255748** [comment]
你是已经解决问题了吗? 同问题.使用disabled属性勉强实现,但是太不美观了.

**Comment by fisher-zwl** [comment]
没有呢，有几个人问了我就把它关了

**Comment by lllomh** [comment]
> 你是已经解决问题了吗? 同问题.使用disabled属性勉强实现,但是太不美观了.

请问 disabled 怎么使用?: 写在哪里?
