### ISSUE TITLE
页面跳转前总会滚动到顶部

### ISSUE THREAD

**Issue by zhanglongjiZLJ** [StructureBuilder/react-keep-alive#67]
页面跳转前总会滚动到顶部，然后跳转过去，返回的时候也是先到顶部，然后再显示到上次浏览的位置，该怎么解决

**Comment by xcqwan** [comment]
用bindLifecycle, 在componentWillUnactivate时记录滚动位置，再在componentDidActivate中手动还原

**Comment by lizy0329** [comment]
```
useKeepAliveEffect(() => {
    console.log("mounted");
    return () => {
      console.log(window.pageYoffset");
    };
  })
```
用 react-router Link 跳转，那么 这个 window.pageYoffset 永远为 0 ，实际上是获取了跳转页的 scrollTop 了
