### ISSUE TITLE
Type file declaration on package.json

### ISSUE THREAD

**Issue by himself65** [StructureBuilder/react-keep-alive#69]

**Comment by wong2** [comment]
有的啊

**Comment by himself65** [comment]
> 有的啊

have you ever read my pull_request?

**Comment by wong2** [comment]
@Himself65 那我要说你的issue写的很不明确，_TypeScript 类型支持_ 有吗，有的，我用的好好的

**Comment by himself65** [comment]
> @Himself65 那我要说你的issue写的很不明确，_TypeScript 类型支持_ 有吗，有的，我用的好好的

I didn't reword the issue title because I had fixed it on PR, sorry if bother you

**Comment by ghost** [comment]
why is everything in chinese here tf

**Comment by himself65** [comment]
Closed as this project has abandoned
