### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by bai3** [StructureBuilder/react-keep-alive#7]
import 的时候出现这个问题，按照文档来的，结果报错了。中午用的还好好的。请问是什么原因造成的。重新安装npm包也是失败的

**Comment by Sam618** [comment]
@bai3 能给我看看什么错吗

**Comment by bai3** [comment]
Uncaught SyntaxError: Unexpected identifier。就是这个报错。运行的时候报错的。然后我就换了react-router-cache-route这个库用来实现效果

**Comment by Sam618** [comment]
@bai3 这个错我没法看出到底是哪里的问题耶😂，能给我一个可以复现的实例吗？

**Comment by bai3** [comment]
不能，我也不知道什么错，突然就gg了。本来可以流畅的使用的

**Comment by Sam618** [comment]
@bai3 安装的是 1.2.0 版本吗😂
