### ISSUE TITLE
退出登录，清除token，页面崩溃（graphql）

### ISSUE THREAD

**Issue by RealReignLiu** [StructureBuilder/react-keep-alive#78]
使用graphql时，app退出登录，清除token，被keep-alive缓存的组件会不断执行组件内的graphql请求，导致页面崩溃

**Comment by Archdemonllllll** [comment]
> 使用graphql时，app退出登录，清除token，被keep-alive缓存的组件会不断执行组件内的graphql请求，导致页面崩溃
