### ISSUE TITLE
浏览器按刷新键,状态还能保存吗?我尝试了几天的react-keep-alive都没有成功

### ISSUE THREAD

**Issue by LastStranger** [StructureBuilder/react-keep-alive#8]
window.location.href这种跳转,返回还能缓存吗?
跳转之后返回是不是不应该触发componentDidMount?但是每次都触发了这个生命周期,

**Comment by LastStranger** [comment]
window.location.href这种跳转,返回能保存状态吗? 还是说只能在组件之间跳转的时候保存状态 ?

**Comment by Sam618** [comment]
> window.location.href这种跳转,返回还能缓存吗?
> 跳转之后返回是不是不应该触发componentDidMount?但是每次都触发了这个生命周期,

#5 可以在这里得到答案，希望提出一些改善建议😄

**Comment by Sam618** [comment]
> window.location.href这种跳转,返回能保存状态吗? 还是说只能在组件之间跳转的时候保存状态 ?

是的只能在组件之间跳转时使用，window.location.href 跳转相当于刷新页面，可以看这篇文章 [https://github.com/Sam618/Blog/issues/3](https://github.com/Sam618/Blog/issues/3)
